### PR TITLE
Add support for iPhone XR, XS and XS Max

### PR DESCRIPTION
**Pull request by doug-sheridan**
iPhone XR:
{"fontScale":1,"width":414,"height":896,"scale":2}

iPhone XS:
{"fontScale":1,"width":414,"height":896,"scale":2}

iPhone XS Max:
{"fontScale":1,"width":414,"height":896,"scale":3}

### CODE REVIEW

**Comment by ptelad** [comment]
Did they really change the height from the iPhone X? Seems weird to me.
I'll check everything once I'm back from vacation next week.

**Comment by doug-sheridan** [comment]
> Did they really change the height from the iPhone X? Seems weird to me.
> I'll check everything once I'm back from vacation next week.

Yessir they did :) See for yourself:
https://www.apple.com/iphone-xs/

**Comment by iRoachie** [comment]
See similar PR made here for the helper library react-navigation uses https://github.com/react-community/react-native-safe-area-view/pull/44

**Comment by lfkwtz** [comment]
> > Did they really change the height from the iPhone X? Seems weird to me.
> > I'll check everything once I'm back from vacation next week.
> 
> Yessir they did :) See for yourself:
> https://www.apple.com/iphone-xs/

To clarify, the XR and XS Max have a height of 896.
X and XS are 812

```
iPhone XR:
{"fontScale":1,"width":414,"height":896,"scale":2}

iPhone XS:
{"fontScale":1,"width":375,"height":812,"scale":3}

iPhone XS Max:
{"fontScale":1,"width":414,"height":896,"scale":3}
```

**Comment by kamiranoff** [comment]
Very nice! But what about the function's name `isIphoneX`. Should you change that too?

**Comment by rstims** [comment]
@kamiranoff agreed, maybe two or three helper functions, one for `812` one for `896` and one for both?

**Comment by ptelad** [comment]
What's the point?
It's the X family... will you have a different design for the XR and XS Max?

**Comment by rstims** [comment]
@ptelad yes

**Comment by kamiranoff** [comment]
`isPhoneX` suggest `iPhone X` not `iPhone X family`.
Just an observation.

**Comment by kamiranoff** [comment]
I called my function `isPhoneXAndAbove`. Which is quite not correct but naming is so complicated as developer...

**Comment by ptelad** [comment]
merged and published to npm.

@kamiranoff @rstims - please open an issue and let's discuss function names there, thank you.

**Pull request merged**
