### PR TITLE
Remove unnecessary parantheses

### PR DESCRIPTION
**Pull request by eriklumme**
Parentheses unnecessary and do not add clarity

### CODE REVIEW

**Comment by ptelad** [comment]
I am not sure I agree, they help the reader to distinct the 2 different sizes.

**Comment by gxsshallot** [comment]
They are the same. `((a || b) || (c || d))` and `(a || b || c || d)` is `true` when there is one `true` value in a, b, c, d.

**Comment by ptelad** [comment]
I do not argue that they are not the same, I do argue that they help with understanding

**Comment by mtzluisalfredo** [comment]
export function isIphoneX() {
  const dimen = Dimensions.get('window');
  const sizes = [812, 896];

  return (
    Platform.OS === 'ios'
    && !Platform.isPad
    && !Platform.isTVOS
    && (sizes.includes(dimen.height) || sizes.includes(dimen.width))
  );
}

@ptelad This can be another way to solve it?

**Comment by mtzluisalfredo** [comment]
```javascript
export function isIphoneX() {
  const dimen = Dimensions.get('window');
  const sizes = [812, 896];

  return (
    Platform.OS === 'ios'
    && !Platform.isPad
    && !Platform.isTVOS
    && (sizes.includes(dimen.height) || sizes.includes(dimen.width))
  );
}
```

@ptelad This can be another way to solve it?

**Comment by ptelad** [comment]
> ```js
> export function isIphoneX() {
>   const dimen = Dimensions.get('window');
>   const sizes = [812, 896];
> 
>   return (
>     Platform.OS === 'ios'
>     && !Platform.isPad
>     && !Platform.isTVOS
>     && (sizes.includes(dimen.height) || sizes.includes(dimen.width))
>   );
> }
> ```
> 
> @ptelad This can be another way to solve it?

I like this solution a lot!

**Pull request closed without merging**
